### ISSUE TITLE
Remove unnecessary columns from output dataset for CERF

### ISSUE THREAD

**Issue by kmongird** [JGCRI/gcamextractor#17]
Some of the columns created in [readgcam.R](https://github.com/JGCRI/gcamextractor/blob/main/R/readgcam.R) to generate the gcamDataTable_extended output either don't change based on any other factor (i.e., they have the same value for every row) and/or they are irrelevant for CERF's purposes. This includes the following columns:

1.	Sources
2.	Aggregate
3.	classPalette1
4.	classLabel2
5.	classPalette2
6.	origScen
7.	xlabel

Removing these from the output would make interpretation of the data easier.

**Comment by zarrarkhan** [comment]
`readgcam.R` produces two tables that are equivalent but with different columns:
- gcamDataTable_Extended.csv: with all columns that are used by other models
- gcamDataTable.csv: Which has selected columns and drops the extra columns that you point out above.

`gcamDataTable.csv` does still contain `classLabel2` and `xLabel` which may be important if we include additional two class parameters or segments where the x parameter is not a year but a segment. 

Please see if `gcamDataTable.csv` is easier to work with. If not we can have `readgcam.R` remove the two remaining extra columns for CERF.

**Comment by kmongird** [comment]
Got it. I think working with `gcamDataTable.csv` will be just fine. I'm also okay with leaving the classlabel2 and xlabel columns for now.
