### ISSUE TITLE
Add Capacity Factor to Energy (EJ) to Capacity (GW) Conversion Calculation

### ISSUE THREAD

**Issue by kmongird** [JGCRI/gcamextractor#23]
The conversion between energy (EJ) to capacity (GW) in [readgcam.R](https://github.com/JGCRI/gcamextractor/blob/main/R/readgcam.R), shown below, is assuming a 100% capacity factor for all technologies (i.e., it is assumed to be operating all 8760 hours).

`value = (value*277.77777777778*1000/8760)`

If the EJ value that GCAM-USA is calculating is energy required to meet energy demand (load) per year, then the required capacity to produce that energy needs to take each technology's capacity factor into account.

For example, working backwards from an individual power plant's capacity to the energy generated:

```
plant_capacity_gw = 1
capacity_factor = 0.50
hours_per_year = 8760
gwh_to_ej_conversion = 0.0000036

# calculate energy generated per year (gwh) by power plant
energy_per_year_gwh = plant_capacity_gw  * (capacity_factor  * hours_per_year )

# convert energy generated from GWh per year to EJ per year
EJ_per_year = energy_per_year_gwh * gwh_to_ej_conversion 
```

The EJ to GW conversion calculation needs to factor in the investment-level capacity factor for each technology type, as follows:

`value = (value*277.77777777778*1000/(capacity_factor*8760))`

Not including capacity factor will mean that CERF will site an inadequate number of power plants to meet energy demand.

**Comment by zarrarkhan** [comment]
The query used for this parameter in GCAM assumes that '1 EJ-capacity' is the ability to generate an EJ in a year if operating at 100% capacity factor for the whole year (full power for a year).  So we do not need to apply a CF to get power capacity in this case.
